// 自动生成: OBS 字段中文标签(源 filter_properties.cpp + data/locale/zh-CN.ini)
const FIELD_LABELS = {
 "toggle_inference": "切换推理",
 "inference_status": "推理状态",
 "model_group": "模型配置",
 "model_path": "模型路径",
 "model_version": "模型版本",
 "use_gpu": "使用GPU",
 "input_resolution": "输入分辨率",
 "num_threads": "#CPU线程",
 "detection_group": "检测配置",
 "confidence_threshold": "置信度阈值",
 "nms_threshold": "NMS阈值",
 "target_class": "目标类别",
 "inference_interval_frames": "推理间隔帧数",
 "render_group": "渲染配置",
 "show_detection_results": "显示检测结果",
 "bbox_line_width": "线宽",
 "bbox_color": "框颜色",
 "label_font_scale": "标签字体大小",
 "region_group": "区域检测",
 "use_region": "使用区域检测",
 "region_x": "区域X坐标",
 "region_y": "区域Y坐标",
 "region_width": "区域宽度",
 "region_height": "区域高度",
 "advanced_group": "高级配置",
 "export_coordinates": "导出坐标",
 "coordinate_output_path": "坐标输出路径",
 "fov_group": "视场设置",
 "show_fov": "显示视场",
 "fov_radius": "视场半径",
 "show_fov_circle": "显示视场圆圈",
 "show_fov_cross": "显示视场十字线",
 "fov_cross_line_scale": "十字线长度",
 "fov_cross_line_thickness": "十字线粗细",
 "fov_circle_thickness": "圆圈粗细",
 "fov_color": "视场颜色",
 "floating_window_group": "悬浮窗",
 "show_floating_window": "显示悬浮窗",
 "floating_window_width": "窗口宽度",
 "floating_window_height": "窗口高度",
 "avg_inference_time": "平均推理时间",
 "detected_objects": "检测到的对象",
 "settings_page": "设置页面",
 "use_gpu_texture_inference": "启用GPU纹理推理",
 "target_classes_text": "目标类别(多个用逗号分隔)",
 "fov2_group": "动态FOV设置",
 "use_dynamic_fov": "启用动态FOV",
 "show_fov2": "显示第二个FOV",
 "fov_radius2": "第二个FOV半径",
 "fov_color2": "第二个FOV颜色",
 "dynamic_fov_shrink_percent": "动态FOV缩放百分比",
 "dynamic_fov_transition_time": "动态FOV过渡时间",
 "use_kalman_tracker": "启用卡尔曼追踪",
 "kalman_generate_threshold": "追踪确认阈值",
 "kalman_terminate_count": "追踪丢失阈值",
 "show_kalman_predictions": "显示预测位置",
 "kalman_prediction_frames": "预测帧数",
 "show_kalman_trajectories": "显示预测轨迹",
 "enable_neural_path": "启用神经网络轨迹",
 "neural_path_points": "轨迹点数量",
 "neural_mouse_step_size": "鼠标步长",
 "neural_target_radius": "目标半径",
 "neural_consume_per_frame": "每帧消费点数",
 "enable_neural_path_debug": "神经网络调试日志",
 "mouse_config_select": "配置选择",
 "test_makcu_connection": "测试MAKCU连接",
 "tracking_group": "目标追踪设置",
 "iou_threshold": "IoU阈值",
 "max_lost_frames": "最大丢失帧数",
 "target_switch_delay": "转火延迟(ms)",
 "target_switch_tolerance": "切换容差",
 "tracking_weight_iou": "IoU权重",
 "tracking_weight_center": "中心点权重",
 "tracking_weight_aspect": "宽高比权重",
 "tracking_weight_area": "面积权重",
 "max_reidentify_frames": "重识别帧数",
 "reidentify_center_threshold": "重识别距离阈值",
 "show_pid_debug_window": "显示PID调试曲线",
 "show_track_id_in_floating_window": "显示目标ID",
 "config_management_group": "配置管理",
 "save_config": "保存配置",
 "load_config": "加载配置",
 "dml_stats": "DML直推统计",
 "algorithm_type_global": "控制算法",
 "external_pid_group": "专业PID配置",
 "external_kp_x": "X轴-Kp",
 "external_ki_x": "X轴-Ki",
 "external_kd_x": "X轴-Kd",
 "external_kp_y": "Y轴-Kp",
 "external_ki_y": "Y轴-Ki",
 "external_kd_y": "Y轴-Kd",
 "external_predict_x": "X轴-预测参数",
 "external_predict_y": "Y轴-预测参数",
 "external_rate_x": "X轴-采样率",
 "external_rate_y": "Y轴-采样率",
 "external_ki_mode": "积分模式",
 "external_kp_limit": "P项限幅",
 "external_ki_limit": "I项限幅",
 "external_kd_limit": "D项限幅",
 "external_output_limit": "总输出限幅",
 "external_ki_rate": "积分速率",
 "external_ki_deadband": "积分死区",
 "aim_controller_group": "aim 控制器配置",
 "crosshair_group": "准星检测",
 "crosshair_enabled": "启用准星检测",
 "crosshair_pick_color": "🎯 吸管取色（点击自动采集准星颜色）",
 "crosshair_color_info": "取色结果",
 "crosshair_manual_r": "准星颜色 R",
 "crosshair_manual_g": "准星颜色 G",
 "crosshair_manual_b": "准星颜色 B",
 "crosshair_apply_rgb": "✅ 应用RGB颜色（转换为HSV范围）",
 "crosshair_h_min": "H最小",
 "crosshair_h_max": "H最大",
 "crosshair_s_min": "S最小",
 "crosshair_s_max": "S最大",
 "crosshair_v_min": "V最小",
 "crosshair_v_max": "V最大",
 "crosshair_h_tolerance": "H容差",
 "crosshair_s_tolerance": "S容差",
 "crosshair_v_tolerance": "V容差",
 "crosshair_morph_kernel": "形态学核大小",
 "crosshair_erode_iter": "腐蚀迭代次数",
 "crosshair_dilate_iter": "膨胀迭代次数",
 "crosshair_grid_rows": "网格行数",
 "crosshair_grid_cols": "网格列数",
 "crosshair_quantile_threshold": "分位数阈值",
 "crosshair_template_path": "模板图片路径",
 "crosshair_match_threshold": "匹配阈值",
 "crosshair_min_area": "最小面积",
 "crosshair_max_area": "最大面积",
 "crosshair_shape_filter_enabled": "启用形状过滤",
 "crosshair_shape_type": "准心形状",
 "crosshair_min_fill_ratio": "最小填充率",
 "crosshair_max_fill_ratio": "最大填充率",
 "crosshair_min_aspect_ratio": "最小纵横比",
 "crosshair_max_aspect_ratio": "最大纵横比",
 "crosshair_search_radius": "搜索半径",
 "crosshair_detect_interval": "检测帧间隔",
 "crosshair_color_isolation": "🎨 颜色隔离视图",
 "crosshair_debug_mask": "显示HSV掩码调试"
};

// 槽键标签(OBS 以 _%d 后缀;此处为 base 名)
const SLOT_LABELS = {
  enable_config: "启用配置", continuous_aim: "持续瞄准", hotkey: "热键",
  controller_type: "鼠标控制方式", mouse_method: "鼠标方法", makcu_port: "MAKCU串口",
  makcu_baud_rate: "MAKCU波特率", logi_driver_type: "Logi驱动类型",
  global_hotkey: "全局热键", global_mouse_enabled: "全局鼠标启用",
  global_kp: "全局Kp", global_ki: "全局Ki", global_kd: "全局Kd",
  p_min: "最小P增益", p_max: "最大P增益", p_slope: "P增益斜率",
  d: "D增益", i: "I增益", derivative_filter_alpha: "导数滤波系数",
  adaptive_p_gain_rate: "自适应P增益速率", d_term_scale: "D项缩放",
  target_y_offset: "目标Y偏移", max_pixel_move: "最大像素移动",
  dead_zone_pixels: "死区像素", screen_offset_x: "屏幕偏移X", screen_offset_y: "屏幕偏移Y",
  screen_width: "屏幕宽度", screen_height: "屏幕高度",
  enable_y_axis_unlock: "启用Y轴解锁", y_axis_unlock_delay: "Y轴解锁延迟",
  integral_limit: "积分限幅", integral_rate: "积分速率",
  p_gain_ramp_initial_scale: "P增益斜坡初始比例", p_gain_ramp_duration: "P增益斜坡时间",
  prediction_weight_x: "预测权重X", prediction_weight_y: "预测权重Y",
  max_prediction_time: "最大预测时间",
  trigger_radius: "扳机半径", trigger_cooldown: "扳机冷却",
  trigger_fire_delay: "扳机发射延迟", trigger_fire_duration: "扳机发射时长",
  trigger_interval: "扳机间隔", enable_trigger_delay_random: "启用延迟随机",
  trigger_delay_random_min: "延迟随机最小", trigger_delay_random_max: "延迟随机最大",
  enable_trigger_duration_random: "启用时长随机", trigger_duration_random_min: "时长随机最小",
  trigger_duration_random_max: "时长随机最大", trigger_move_compensation: "移动补偿",
  recoil_strength: "后坐力强度", recoil_speed: "后坐力速度",
  recoil_pid_gain_scale: "后坐PID增益缩放",
  smith_model_gain: "Smith模型增益", smith_model_tau: "Smith时间常数",
  smith_auto_tau: "Smith自动Tau",
  slew_rate_output_gain: "限速输出增益", slew_rate_response_smoothing: "响应平滑",
  slew_rate_approach_damping: "趋近阻尼", slew_rate_update_interval_ms: "更新间隔ms",
  slew_rate_normalization_scale: "归一化比例",
  adaptive_pid_kp: "自适应Kp", adaptive_pid_ki: "自适应Ki", adaptive_pid_kd: "自适应Kd",
  adaptive_pid_dead_zone: "死区阈值", adaptive_pid_integral_limit: "积分限幅",
  adaptive_pid_integral_deadzone: "积分死区", adaptive_pid_integral_gain_threshold: "积分自适应阈值",
  adaptive_pid_integral_gain_rate: "积分自适应速率", adaptive_pid_output_limit: "输出限幅",
  bezier_curvature: "贝塞尔曲率", bezier_randomness: "贝塞尔随机性",
  ghost_curvature: "鬼影曲率", ghost_noise_intensity: "噪声强度",
  ghost_vertical_snap: "垂直吸附", ghost_noise_freq: "噪声频率",
  imm_process_noise_pos: "位置过程噪声", imm_process_noise_vel: "速度过程噪声",
  imm_process_noise_acc: "加速度过程噪声", imm_process_noise_turn: "转弯过程噪声",
  imm_measurement_noise_x: "X测量噪声", imm_measurement_noise_y: "Y测量噪声",
  imm_active_models: "活动模型数",
  one_euro_min_cutoff: "最小截止频率", one_euro_beta: "Beta", one_euro_d_cutoff: "D截止频率",
  aim_smoothing_x: "瞄准平滑X", aim_smoothing_y: "瞄准平滑Y",
  intensity_mode: "强度模式", intensity_value: "强度值", smooth_factor: "平滑系数",
};
