/* OBS filter_properties long_description — keys match OBS property names */
window.OBS_HELP = {
  model_path: "选择 YOLO ONNX 模型文件路径",
  model_version: "选择 YOLO 模型版本（V5/V8/V11 等）",
  use_gpu: "选择推理设备（CUDA / DirectML / CPU）。配置为 CUDA 时若缺 cuDNN 会自动回退 CPU，状态栏显示实际设备。",
  device: "选择推理设备（CUDA / DirectML / CPU）。配置为 CUDA 时若缺 cuDNN 会自动回退 CPU，状态栏显示实际设备。",
  input_resolution: "模型输入分辨率，影响精度和速度",
  input_size: "模型输入分辨率，影响精度和速度",
  num_threads: "CPU 推理线程数，建议设置为物理核心数",
  confidence_threshold: "检测置信度阈值，低于此值的检测结果将被过滤",
  confidence: "检测置信度阈值，低于此值的检测结果将被过滤",
  nms_threshold: "NMS 非极大值抑制阈值，用于去除重叠框",
  nms: "NMS 非极大值抑制阈值，用于去除重叠框",
  target_class: "要检测的目标类别",
  target_classes_text: "指定多个目标类别，用逗号分隔（如：0,1,2）",
  inference_interval_frames: "每隔多少帧进行一次推理，0 表示每帧都推理",
  interval_frames: "每隔多少帧进行一次推理，1 表示每帧都推理",
  show_detection_results: "显示检测结果（边界框、类别标签、置信度）",
  bbox_line_width: "边界框线宽",
  bbox_color: "边界框颜色",
  label_font_scale: "标签字体大小",
  use_region: "只在指定区域内进行检测",
  region_x: "检测区域左上角 X 坐标",
  region_y: "检测区域左上角 Y 坐标",
  region_width: "检测区域宽度",
  region_height: "检测区域高度",
  export_coordinates: "将检测结果坐标导出到 JSON 文件",
  coordinate_output_path: "坐标输出文件路径",
  show_floating_window: "显示独立的置顶预览悬浮窗（可拖动，与 OBS 悬浮窗同语义）",
  preview_enabled: "Web 预览开关。关闭后预览线程跳过画框与 BMP 编码，节省 CPU；不看预览时建议关闭",
  floating_window_width: "悬浮窗宽度",
  floating_window_height: "悬浮窗高度",
  show_track_id_in_floating_window: "在悬浮窗中显示目标 track ID",
  show_fov: "是否显示瞄准 FOV 区域",
  fov_radius: "FOV 半径（像素）",
  show_fov_circle: "是否显示 FOV 圆圈",
  show_fov_cross: "是否显示 FOV 十字线",
  fov_cross_line_scale: "FOV 十字线长度",
  fov_cross_line_thickness: "FOV 十字线粗细",
  fov_circle_thickness: "FOV 圆圈粗细",
  fov_color: "FOV 颜色",
  use_dynamic_fov: "启用动态 FOV，根据目标距离自动调整",
  show_fov2: "是否显示第二个 FOV 区域",
  fov_radius2: "第二个 FOV 半径（像素）",
  fov_color2: "第二个 FOV 颜色",
  dynamic_fov_shrink_percent: "动态 FOV 缩放到原 FOV 的百分比（例如：50 表示缩小到 50%）",
  dynamic_fov_transition_time: "动态 FOV 过渡动画时间（毫秒），0 立即切换，100 线性，100–500 缓动",
  use_kalman_tracker: "启用卡尔曼滤波器进行目标追踪，提供更稳定的目标 ID 和预测能力",
  kalman_generate_threshold: "目标需要连续检测到的帧数才能被确认追踪",
  kalman_terminate_count: "目标丢失多少帧后停止追踪",
  show_kalman_predictions: "在画面上显示卡尔曼滤波器预测的目标位置（青色虚线框）",
  kalman_prediction_frames: "卡尔曼滤波器预测的未来帧数，用于显示预测轨迹",
  show_kalman_trajectories: "在画面上显示卡尔曼滤波器预测的轨迹线（黄色）",
  enable_neural_path: "启用神经网络轨迹生成器，生成更自然的鼠标移动轨迹",
  neural_path_points: "轨迹点数量，越多越平滑但移动越慢",
  neural_mouse_step_size: "每次移动的步长大小",
  neural_target_radius: "到达目标的判定半径",
  neural_consume_per_frame: "每帧消费的路径点数量，越大移动越快但曲线越粗略（1=拟人,2=平衡,3+=快速）",
  enable_neural_path_debug: "开启后会输出详细的神经网络轨迹运行日志，用于调试",
  enable_config: "启用当前鼠标控制配置",
  continuous_aim: "启用后无需按住热键，自动持续瞄准目标",
  hotkey: "激活此配置的热键",
  controller_type: "鼠标控制：WindowsAPI=系统 API，MAKCU=串口，Logi=内核驱动，GvInput=网易 WHQL HID，NtUser*=底层注入",
  logi_driver_type: "驱动子类型：自动检测优先尝试所有驱动，或强制指定特定驱动",
  makcu_port: "MAKCU 串口端口号（如 COM5）",
  makcu_baud_rate: "MAKCU 串口波特率",
  p_min: "最小比例增益，远距离时使用",
  p_max: "最大比例增益，近距离时使用",
  p_slope: "距离-增益曲线斜率，控制 P 值随距离变化的敏感度",
  d: "微分增益，控制对误差变化率的响应。值越大响应越快但容易抖动",
  i: "积分增益，用于消除稳态误差。值越大消除误差越快但容易超调",
  derivative_filter_alpha: "微分滤波系数，用于平滑 D 项，减少抖动",
  adaptive_p_gain_rate: "自适应 P 增益变化率（对应专业 PID 的预测参数），值越大 P 增益调整越快",
  d_term_scale: "D 项缩放因子（对应专业 PID 的采样率），值越大 D 项影响越大",
  target_y_offset: "目标 Y 轴偏移量（相对于目标框高度的百分比），正值向上，负值向下",
  max_pixel_move: "单次最大移动像素数，限制最大移动速度",
  dead_zone_pixels: "瞄准死区，误差小于此值时不移动鼠标",
  screen_offset_x: "屏幕中心 X 轴偏移量，用于校准瞄准点",
  screen_offset_y: "屏幕中心 Y 轴偏移量，用于校准瞄准点",
  screen_width: "屏幕分辨率宽度，0 表示自动检测",
  screen_height: "屏幕分辨率高度，0 表示自动检测",
  enable_y_axis_unlock: "长按热键一段时间后临时解锁 Y 轴移动",
  y_axis_unlock_delay: "Y 轴解锁延迟时间（毫秒）",
  autoTriggerRadius: "自动扳机触发半径（像素）",
  autoTriggerCooldown: "两次自动点击之间的最小间隔（毫秒）",
  autoTriggerFireDelay: "检测到目标后延迟多久开火（毫秒）",
  autoTriggerFireDuration: "鼠标按下持续时间（毫秒）",
  autoTriggerInterval: "自动扳机触发间隔（毫秒）",
  enableTriggerDelayRandom: "启用随机开火延时，增加不可预测性",
  triggerDelayRandomMin: "随机开火延时的下限",
  triggerDelayRandomMax: "随机开火延时的上限",
  enableTriggerDurationRandom: "启用随机开火时长",
  triggerDurationRandomMin: "随机开火时长的下限",
  triggerDurationRandomMax: "随机开火时长的上限",
  triggerMoveCompensation: "移动补偿像素数，用于补偿鼠标移动时的延迟",
  integral_limit: "积分项上限，防止积分饱和",
  integral_rate: "积分增长速率系数，值越大积分越快",
  p_gain_ramp_initial_scale: "P-Gain Ramp 初始比例，热键按下初期使用较低的 P 值",
  p_gain_ramp_duration: "P-Gain Ramp 持续时间，从初始比例过渡到 100% 的时间",
  recoilStrength: "每次压枪移动的像素数，值越大压枪幅度越大",
  recoilSpeed: "压枪移动的时间间隔（毫秒），值越小压枪频率越高",
  recoilPidGainScale: "压枪时 Y 轴 PID 控制的增益系数，0=完全禁用 Y 轴 PID，1=保持原增益",
  prediction_weight_x: "导数预测器在 X 轴的融合权重，值越大预测效果越强",
  prediction_weight_y: "导数预测器在 Y 轴的融合权重，值越大预测效果越强",
  max_prediction_time: "最大预测时间（秒）",
  algorithm_type_global: "全局算法类型：Advanced / ExternalPID / AimController / SlewRate / Adaptive",
  aim_enabled: "总开关：是否启用瞄准栈",
  crosshair_enabled: "启用准星检测，用画面准星位置作为瞄准原点",
  capture_backend: "截图后端：DXGI Desktop Duplication / WGC / GDI",
  capture_mode: "center=屏幕正中裁切（非全屏）；region=固定左上角 ROI",
  width: "截图宽度（像素）。推理在此裁切区域上运行，不是整屏",
  height: "截图高度（像素）",
  backend: "截图后端：DXGI Desktop Duplication / WGC / GDI",
  mode: "center=屏幕正中裁切（非全屏）；region=固定左上角 ROI",
  iou_threshold: "跟踪匹配 IOU 阈值",
  max_lost_frames: "目标连续丢失多少帧后删除轨迹",
  max_reidentify_frames: "丢失后允许重识别的最大帧数",
  reidentify_center_threshold: "重识别时中心距离阈值（归一化）",
  tracking_weight_iou: "Hungarian 代价中 IOU 权重",
  tracking_weight_center: "Hungarian 代价中心距离权重",
  tracking_weight_aspect: "Hungarian 代价宽高比权重",
  tracking_weight_area: "Hungarian 代价面积权重",
  smith_model_gain: "Smith 预测器模型增益",
  smith_model_tau: "Smith 预测器时间常数 τ",
  smith_auto_tau: "根据推理延迟自动估计 τ",
  use_one_euro_filter: "启用 One Euro 滤波器平滑瞄准输出",
  one_euro_min_cutoff: "One Euro 最小截止频率",
  one_euro_beta: "One Euro 速度系数 β",
  one_euro_d_cutoff: "One Euro 导数截止频率",
  bezier_curvature: "Bezier 轨迹曲率",
  bezier_randomness: "Bezier 轨迹随机扰动",
  ghost_curvature: "Ghost 轨迹曲率",
  ghost_noise_intensity: "Ghost 噪声强度",
  ghost_vertical_snap: "Ghost 垂直吸附",
  ghost_noise_freq: "Ghost 噪声频率",
  prediction_weight_x: "导数预测器 X 轴融合权重",
  prediction_weight_y: "导数预测器 Y 轴融合权重",
  max_prediction_time: "最大预测时间（秒）",
};

window.OBS_LABEL = {
  model_path: "模型路径",
  model_version: "模型版本",
  use_gpu: "推理设备",
  device: "推理设备",
  input_resolution: "输入分辨率",
  input_size: "输入分辨率",
  num_threads: "线程数",
  confidence_threshold: "置信度阈值",
  confidence: "置信度阈值",
  nms_threshold: "NMS 阈值",
  nms: "NMS 阈值",
  inference_interval_frames: "推理间隔帧",
  interval_frames: "推理间隔帧",
  show_fov: "显示 FOV",
  fov_radius: "FOV 半径",
  show_fov_circle: "显示 FOV 圆",
  show_fov_cross: "显示 FOV 十字",
  fov_cross_line_scale: "十字线长度",
  fov_cross_line_thickness: "十字线粗细",
  fov_circle_thickness: "圆圈粗细",
  use_dynamic_fov: "启用动态 FOV",
  show_fov2: "显示 FOV2",
  fov_radius2: "FOV2 半径",
  dynamic_fov_shrink_percent: "动态 FOV 收缩 %",
  dynamic_fov_transition_time: "动态 FOV 过渡 ms",
  continuous_aim: "持续自瞄",
  enable_config: "启用此配置",
  hotkey: "热键",
  controller_type: "控制方式",
  makcu_port: "MAKCU 串口",
  makcu_baud_rate: "MAKCU 波特率",
  logi_driver_type: "Logi 驱动类型",
  dead_zone_pixels: "瞄准死区",
  max_pixel_move: "最大移动量",
  target_y_offset: "Y 轴目标偏移",
  enable_y_axis_unlock: "Y 轴解锁",
  y_axis_unlock_delay: "Y 轴解锁延迟",
  screen_offset_x: "屏幕中心 X 偏移",
  screen_offset_y: "屏幕中心 Y 偏移",
  screen_width: "屏幕宽度",
  screen_height: "屏幕高度",
  p_min: "最小比例增益",
  p_max: "最大比例增益",
  p_slope: "距离-增益斜率",
  d: "微分增益 D",
  i: "积分增益 I",
  derivative_filter_alpha: "微分滤波系数",
  adaptive_p_gain_rate: "自适应 P 增益变化率",
  d_term_scale: "D 项缩放",
  integral_limit: "积分限幅",
  integral_rate: "积分速率",
  p_gain_ramp_initial_scale: "P 增益爬升初值",
  p_gain_ramp_duration: "P 增益爬升时长",
  autoTriggerRadius: "触发半径",
  autoTriggerCooldown: "冷却时间",
  autoTriggerFireDelay: "开火延迟",
  autoTriggerFireDuration: "开火时长",
  autoTriggerInterval: "触发间隔",
  enableTriggerDelayRandom: "延迟随机",
  triggerDelayRandomMin: "延迟随机下限",
  triggerDelayRandomMax: "延迟随机上限",
  enableTriggerDurationRandom: "时长随机",
  triggerDurationRandomMin: "时长随机下限",
  triggerDurationRandomMax: "时长随机上限",
  triggerMoveCompensation: "移动补偿",
  autoRecoilControlEnabled: "启用后座控制",
  recoilStrength: "压枪幅度",
  recoilSpeed: "压枪间隔",
  recoilPidGainScale: "压枪 PID 增益",
  algorithm_type_global: "算法类型",
  aim_enabled: "启用瞄准",
  crosshair_enabled: "启用准星检测",
  backend: "截图后端",
  mode: "截图模式",
  width: "截图宽度",
  height: "截图高度",
};
