name: Feature Request
description: Suggest an idea or improvement for this project
labels: enhancement
assignees: umireon
body:
  - type: markdown
    id: md_welcome
    attributes:
      value: |
        ## 💡 Feature Request for Live Background Removal Lite

        Please fill out the form below to suggest a new feature or improvement.
        - Check existing issues before submitting a new one.
        - Provide as much detail as possible.

        **Note:** Developers are human too—please be polite and respectful in your communication.
        Also, please understand that development time and resources are limited.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem you are experiencing. (If not, you can leave this blank.)
      placeholder: "I'm always frustrated when ..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What do you want to happen? Please be as specific as possible.
      placeholder: "I would like to see ..."
    validations:
      required: true

  - type: textarea
    id: technical_basis
    attributes:
      label: Technical Justification / Feasibility
      description: |
        Please explain why you believe this feature is technically feasible, or provide ideas on how it could be implemented.
        (For example: reference to APIs, libraries, similar plugins, or technical documentation.)
      placeholder: "This should be possible because ... (e.g., OBS provides an API for ..., or similar functionality exists in ...)"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context, links, or screenshots about the feature request here.
    validations:
      required: false
